repos:
  - repo: local
    hooks:
      - id: run-pytest
        name: Run pytest with Poetry
        entry: poetry run pytest
        language: system
        types: [python]
        pass_filenames: false
